BEGIN;
CREATE TABLE PERFORMERS (
	id SERIAL PRIMARY KEY,
	perf_name VARCHAR(50) NOT NULL
);
CREATE TABLE ALBUMS (
	id SERIAL PRIMARY KEY,
	alb_name VARCHAR(50) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	perf_id INTEGER REFERENCES PERFORMERS (id)ON DELETE CASCADE NOT NULL 
);
CREATE TABLE TRACKS (
	id SERIAL PRIMARY KEY,
	track_name VARCHAR(50) NOT NULL,
	track_len INTEGER NOT NULL,
	alb_id INTEGER REFERENCES ALBUMS (id)ON DELETE CASCADE NOT NULL 
);
COMMIT;